project_id = "izxahziuilamkikvrfhi"

[functions.get-weather-astronomy]
verify_jwt = false

[functions.scrape-flights]
verify_jwt = false

[functions.send-notification]
verify_jwt = true

[functions.get-weather]
verify_jwt = false

[functions.track-flight]
verify_jwt = false

[functions.send-web-push]
verify_jwt = true
